'use client';

import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { AlertTriangle, ArrowLeft, Check, History, Loader2, RefreshCw, RotateCcw, Search, ShieldCheck, X } from 'lucide-react';
import { api } from '@/lib/api';

type Candidate = { id:string; personId:string|null; name:string|null; email:string|null; cpfMasked:string|null; phoneMasked:string|null; instagram:string|null; originSource:string|null; store:{code:string;name:string}|null; ltvCents:number; orderCount:number };
type Priority = 'conflict'|'high'|'review';
type Suggestion = { key:string; type:'phone'|'email'|'instagram'; matchMasked:string; participantCount:number; unlinkedCount:number; existingPersonCount:number; totalLtvCents:number; totalOrders:number; candidates:Candidate[]; priority:Priority; score:number; signals:string[]; partial:boolean; siteLive:boolean };
type Decision = { id:string; decision:'confirmed'|'rejected'; suggestionType:string; actorUserId:string|null; reason:string; decidedAt:string; rolledBackAt:string|null; canRollback:boolean; participants:Array<{id:string;name:string|null;originSource:string|null;originStore:{code:string;name:string}|null}> };
const money=(c:number)=>(c/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const priorityLabel:Record<Priority,string>={conflict:'Conflito',high:'Alta confiança',review:'Precisa conferir'};
const priorityStyle:Record<Priority,string>={conflict:'bg-rose-100 text-rose-800',high:'bg-emerald-100 text-emerald-800',review:'bg-amber-100 text-amber-800'};

export default function RevisaoIdentidadePage(){
  const [tab,setTab]=useState<'pending'|'history'>('pending');
  const [items,setItems]=useState<Suggestion[]>([]); const [decisions,setDecisions]=useState<Decision[]>([]);
  const [total,setTotal]=useState(0); const [counters,setCounters]=useState({conflict:0,high:0,review:0});
  const [loading,setLoading]=useState(true); const [acting,setActing]=useState<string|null>(null);
  const [selected,setSelected]=useState<Suggestion|null>(null); const [reason,setReason]=useState(''); const [error,setError]=useState<string|null>(null);
  const [priority,setPriority]=useState(''); const [type,setType]=useState(''); const [channel,setChannel]=useState(''); const [linkState,setLinkState]=useState(''); const [search,setSearch]=useState('');

  const load=useCallback(async()=>{ setLoading(true);setError(null);try{
    if(tab==='history'){
      const r=await api<{total:number;items:Decision[]}>('/customers-crm/identity-review-history?limit=100'); setDecisions(r.items);setTotal(r.total);
    }else{
      const q=new URLSearchParams({limit:'100'}); if(priority)q.set('priority',priority);if(type)q.set('type',type);if(channel)q.set('channel',channel);if(linkState)q.set('linkState',linkState);if(search.trim())q.set('search',search.trim());
      const r=await api<{total:number;items:Suggestion[];counters:typeof counters}>(`/customers-crm/identity-review?${q}`);setItems(r.items);setTotal(r.total);setCounters(r.counters);
    }
  }catch(e:any){setError(e?.message||'Não foi possível carregar os dados');}finally{setLoading(false);}},[tab,priority,type,channel,linkState,search]);
  useEffect(()=>{const timer=setTimeout(load,search?300:0);return()=>clearTimeout(timer);},[load,search]);

  const decide=async(decision:'confirm'|'reject')=>{if(!selected||reason.trim().length<3){setError('Informe um motivo com pelo menos 3 caracteres.');return;}setActing(decision);try{await api(`/customers-crm/identity-review/${encodeURIComponent(selected.key)}/${decision}`,{method:'POST',body:JSON.stringify({reason:reason.trim()})});setSelected(null);setReason('');await load();}catch(e:any){setError(e?.message||'A decisão não pôde ser salva');}finally{setActing(null);}};
  const rollback=async(d:Decision)=>{if(!window.confirm('Desfazer esta confirmação? Vínculos alterados depois dela serão preservados.'))return;setActing(d.id);try{await api(`/customers-crm/identity-review/decisions/${d.id}/rollback`,{method:'POST'});await load();}catch(e:any){setError(e?.message||'Não foi possível desfazer');}finally{setActing(null);}};
  const filters=[['priority',priority,setPriority,[['','Todas prioridades'],['conflict','Conflitos'],['high','Alta confiança'],['review','Precisa conferir']]],['type',type,setType,[['','Telefone + E-mail + Instagram'],['phone','Telefone'],['email','E-mail'],['instagram','Instagram']]],['channel',channel,setChannel,[['','Todos os canais'],['site-live','Site + Live']]],['link',linkState,setLinkState,[['','Todos os vínculos'],['partial','Parcialmente vinculada'],['unlinked','Sem pessoa']]]] as const;

  return <main className="min-h-screen bg-slate-50 p-4 sm:p-6"><div className="mx-auto max-w-6xl space-y-5">
    <header className="flex flex-wrap items-center justify-between gap-3"><div><Link href="/retaguarda" className="mb-2 inline-flex items-center gap-1 text-sm text-slate-500"><ArrowLeft className="h-4 w-4"/> Voltar</Link><h1 className="flex items-center gap-2 text-2xl font-black"><ShieldCheck className="h-6 w-6 text-violet-600"/> Revisão de identidade</h1><p className="text-sm text-slate-600">Revisão humana e auditada. Nenhuma compra, parcela ou marcado é movimentado.</p></div><button onClick={load} disabled={loading} className="inline-flex items-center gap-2 rounded-lg border bg-white px-3 py-2 text-sm font-bold"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/>Atualizar</button></header>
    <div className="flex gap-2 border-b"><button onClick={()=>setTab('pending')} className={`px-4 py-2 text-sm font-bold ${tab==='pending'?'border-b-2 border-violet-600 text-violet-700':'text-slate-500'}`}>Pendentes</button><button onClick={()=>setTab('history')} className={`flex items-center gap-1 px-4 py-2 text-sm font-bold ${tab==='history'?'border-b-2 border-violet-600 text-violet-700':'text-slate-500'}`}><History className="h-4 w-4"/>Histórico</button></div>
    {error&&<div className="flex gap-2 rounded-xl border border-rose-300 bg-rose-50 p-3 text-sm text-rose-900"><AlertTriangle className="h-4 w-4"/>{error}</div>}
    {tab==='pending'&&<><div className="grid gap-2 sm:grid-cols-3">{(['conflict','high','review'] as Priority[]).map(p=><button key={p} onClick={()=>setPriority(priority===p?'':p)} className={`rounded-xl border p-3 text-left ${priority===p?'ring-2 ring-violet-500':'bg-white'}`}><div className="text-2xl font-black">{counters[p]}</div><div className="text-xs font-bold">{priorityLabel[p]}</div></button>)}</div>
      <div className="grid gap-2 rounded-xl border bg-white p-3 md:grid-cols-5"><label className="relative md:col-span-2"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por nome" className="w-full rounded-lg border py-2 pl-9 pr-3 text-sm"/></label>{filters.slice(1).map(([key,value,setter,options])=><select key={key} value={value} onChange={e=>setter(e.target.value)} className="rounded-lg border px-2 py-2 text-sm">{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>)}</div>
      <div className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm"><b>{total} sugestões neste filtro.</b> A prioridade apenas organiza; nunca confirma automaticamente.</div></>}
    {loading&&<div className="flex justify-center p-12"><Loader2 className="h-7 w-7 animate-spin text-violet-600"/></div>}
    {!loading&&tab==='pending'&&<section className="space-y-4">{items.map(g=><article key={g.key} className="overflow-hidden rounded-xl border bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-2 border-b bg-slate-50 px-4 py-3"><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2 py-1 text-xs font-black ${priorityStyle[g.priority]}`}>{priorityLabel[g.priority]} · {g.score}</span><span className="rounded-full bg-violet-100 px-2 py-1 text-xs font-black uppercase text-violet-800">{g.type==='phone'?'Telefone':g.type==='email'?'E-mail':'Instagram'}</span><b>{g.matchMasked}</b></div><div className="text-xs text-slate-600">{g.totalOrders} compras · {money(g.totalLtvCents)} · {g.unlinkedCount} sem pessoa</div></div><div className="flex flex-wrap gap-1 border-b px-4 py-2">{g.signals.map(s=><span key={s} className="rounded bg-slate-100 px-2 py-1 text-[11px] font-bold text-slate-700">{s}</span>)}</div><div className="grid gap-px bg-slate-200 md:grid-cols-2 lg:grid-cols-3">{g.candidates.map(c=><div key={c.id} className="bg-white p-4"><div className="font-black">{c.name||'Sem nome'}</div><div className="mt-1 space-y-0.5 text-xs text-slate-600"><div>{c.cpfMasked||'CPF não informado'}</div><div>{c.phoneMasked||c.instagram||'Contato não informado'}</div><div>{c.email||'E-mail não informado'}</div></div><div className="mt-3 text-xs"><b>Origem:</b> {c.store?`${c.store.code} · ${c.store.name}`:c.originSource||'não informada'}</div><div className="mt-1 text-xs"><b>Histórico:</b> {c.orderCount} compras · {money(c.ltvCents)}</div></div>)}</div><div className="flex justify-end border-t p-3"><button onClick={()=>{setSelected(g);setReason('')}} className="rounded-lg bg-violet-600 px-4 py-2 text-sm font-bold text-white">Revisar decisão</button></div></article>)}</section>}
    {!loading&&tab==='history'&&<section className="space-y-3"><div className="rounded-xl border bg-white p-3 text-sm"><b>{total} decisões registradas.</b></div>{decisions.map(d=><article key={d.id} className="rounded-xl border bg-white p-4"><div className="flex flex-wrap justify-between gap-2"><div><span className={`rounded-full px-2 py-1 text-xs font-black ${d.decision==='confirmed'?'bg-emerald-100 text-emerald-800':'bg-rose-100 text-rose-800'}`}>{d.decision==='confirmed'?'Confirmado':'Rejeitado'}</span><span className="ml-2 text-xs text-slate-500">{new Date(d.decidedAt).toLocaleString('pt-BR')} · {d.suggestionType}</span></div>{d.canRollback&&<button onClick={()=>rollback(d)} disabled={acting===d.id} className="inline-flex items-center gap-1 rounded-lg border px-3 py-1 text-xs font-bold text-amber-800"><RotateCcw className="h-3.5 w-3.5"/>Desfazer</button>}</div><p className="mt-3 text-sm"><b>Motivo:</b> {d.reason}</p><div className="mt-2 text-xs text-slate-600">{d.participants.map(p=>`${p.name||'Sem nome'} (${p.originStore?.code||p.originSource||'origem não informada'})`).join(' · ')}</div>{d.rolledBackAt&&<div className="mt-2 text-xs font-bold text-amber-700">Desfeita em {new Date(d.rolledBackAt).toLocaleString('pt-BR')}</div>}</article>)}</section>}
  </div>
  {selected&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="w-full max-w-lg rounded-2xl bg-white p-5"><h2 className="text-lg font-black">Registrar decisão</h2><p className="mt-1 text-sm text-slate-600">{selected.participantCount} cadastros · {priorityLabel[selected.priority]} · {selected.matchMasked}</p>{selected.priority==='conflict'&&<div className="mt-3 rounded-lg bg-rose-50 p-3 text-sm font-bold text-rose-800">Conflito detectado. A confirmação está bloqueada.</div>}<label className="mt-4 block text-sm font-bold">Motivo obrigatório</label><textarea value={reason} onChange={e=>setReason(e.target.value)} rows={4} className="mt-1 w-full rounded-lg border-2 p-3 text-sm" placeholder="Ex.: nome, contato e histórico conferidos pela matriz"/><div className="mt-4 flex flex-wrap justify-end gap-2"><button onClick={()=>setSelected(null)} disabled={!!acting} className="rounded-lg border px-3 py-2 text-sm font-bold">Cancelar</button><button onClick={()=>decide('reject')} disabled={!!acting} className="inline-flex items-center gap-1 rounded-lg bg-rose-600 px-3 py-2 text-sm font-bold text-white"><X className="h-4 w-4"/>Não é a mesma pessoa</button><button onClick={()=>decide('confirm')} disabled={!!acting||selected.priority==='conflict'} className="inline-flex items-center gap-1 rounded-lg bg-emerald-600 px-3 py-2 text-sm font-bold text-white disabled:opacity-50">{acting==='confirm'?<Loader2 className="h-4 w-4 animate-spin"/>:<Check className="h-4 w-4"/>}Confirmar vínculo</button></div></div></div>}
  </main>;
}
